name: Sample Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install robotframework

      - name: Verify Python version
        run: python --version

      - name: Check Current directory
        run: ls -lrt

      - name: Run test
        run: robot -d logs/ example.robot

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-logs
          path: logs/